apiVersion: apps/v1
kind: Deployment
metadata:
  name: w9-api
  namespace: demo
  labels:
    app: w9-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: w9-api
  template:
    metadata:
      labels:
        app: w9-api
    spec:
      containers:
        - name: api
          image: w9-api:1 # Sử dụng đúng Image bạn vừa nạp ở Lab 2
          imagePullPolicy: Never # QUAN TRỌNG: Ép K8s lấy image có sẵn trong cụm, không kéo từ internet
          ports:
            - containerPort: 8080
          env:
            - name: VERSION
              value: "v1"
            - name: ERROR_RATE
              value: "0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: w9-api-svc
  namespace: demo
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080 # Để có thể truy cập từ bên ngoài máy tính qua Minikube
  selector:
    app: w9-api
  type: NodePort