apiVersion: v1
kind: ConfigMap
metadata:
  name: be-config
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  # Cấu hình Nginx biến thành một Mock API Server trả về dữ liệu JSON
  api.conf: |
    server {
        listen 80;
        
        # Hỗ trợ gọi API xuyên quốc gia (CORS) giúp FE kết nối được BE
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;

        location /api/profile {
            default_type application/json;
            return 200 '{"name": "Thùy Trang", "role": "DevOps Engineer / Fullstack Developer", "skills": ["GitOps", "ArgoCD", "Kubernetes", "AWS", "Docker"], "status": "Kết nối Backend thành công! 🚀"}';
        }

        location / {
            default_type text/plain;
            return 200 'Backend đang hoạt động ổn định!';
        }
    }