apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ThuyTrang9525/gitops.git'
    targetRevision: HEAD
    path: k8s-api # Trỏ chính xác vào thư mục k8s-api chúng ta vừa tạo ở trên
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true