apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 58.2.2
    helm:
      values: |
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
        defaultRules:
          rules:
            kubelet: false
        
        # =========================================================
        # 🔥 ĐOẠN BỔ SUNG: CẤU HÌNH GMAIL CHO ALERTMANAGER TẠI ĐÂY
        # =========================================================
        alertmanager:
          config:
            global:
              smtp_smarthost: 'smtp.gmail.com:587'
              smtp_from: 'buithithuytrang0905@gmail.com' # <--- THAY BẰNG EMAIL GỬI CỦA BẠN
              smtp_auth_username: 'buithithuytrang0905@gmail.com' # <--- THAY BẰNG EMAIL GỬI CỦA BẠN
              smtp_auth_password: 'rheh lbwf mezh mnuy'
              smtp_require_tls: true
            route:
              group_by: ['alertname', 'namespace']
              group_wait: 30s       # ◄--- Tăng lên 30s: Đợi 30s để gom tất cả các alert cùng loại vào 1 mail duy nhất
              group_interval: 5m    # ◄--- SỬA THÀNH 5m (Thay vì 10s): Nếu có alert mới cùng nhóm, phải đợi 5 phút sau mới được gửi tiếp
              repeat_interval: 3h   # ◄--- SỬA THÀNH 3h (Thay vì 5m): Nếu lỗi cũ VẪN BỊ KẸT chưa sửa, phải 3 tiếng sau mới nhắc lại (Tránh ngập lụt mail)
              receiver: 'email-notifications'
              routes:
              - matchers:
                - severity = critical
                receiver: 'email-notifications'
            receivers:
            - name: 'email-notifications'
              email_configs:
              - to: 'buithithuytrang0905@gmail.com'         # <--- THAY BẰNG EMAIL CÁ NHÂN MUỐN NHẬN THƯ
                send_resolved: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true